@base_url = http://localhost:3333
@email = ricardo@teste.com
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDQ5NDkzMjYsImV4cCI6MTYwNTAzNTcyNiwic3ViIjoiM2M2NTNmZDItZDRkMC00ZmVjLWJlNzMtNWFlY2NhMzNiZjFmIn0.wJBtreGAdkhNVqvRa9n0iEtZwNry835D7RVx4KpO94o
### Criar um usuario
POST {{base_url}}/users
content-type: application/json

{
    "name": "Ricardo",
    "email": "{{email}}",
    "password": "123456789"
}

### Esqueçi minha senha
POST {{base_url}}/password/forgot
content-type: application/json

{
	"email": "{{email}}"
}

### Resetar senha
POST {{base_url}}/password/reset
content-type: application/json

{
	"password": "123123",
  "password_confirmation": "123123",
	"token": "3b6527f0-f2d1-43d2-a7a9-010430798c4d"
}

### Logar
POST {{base_url}}/sessions
content-type: application/json

{
	"email": "{{email}}",
	"password": "123123"
}

### Mostrar Perfil
GET {{base_url}}/profile
Authorization: {{token}}


### Atualizar Perfil
PUT {{base_url}}/profile
Authorization: {{token}}
content-type: application/json

{
	"name": "Ricardo",
	"email": "{{email}}",
	"old_password": "123456",
	"password": "123456",
  "password_confirmation": "123456"
}

### Listar provedores
GET {{base_url}}/providers
Authorization: {{token}}

### Criar um agendamento
POST {{base_url}}/appointments
Authorization: {{token}}

content
{
	"provider_id": "d2e8c71a-97f6-453b-91c6-afff01dd4855",
	"date": "{% now 'iso-8601', '' %}"
}

### Listar dias disponiveis
GET {{base_url}}/providers/dffdae8f-fb53-4743-9152-e17367897ded/month-availability
Authorization: {{token}}

content
{
	"month": 12,
	"year": 2020
}

### Listar Horarios disponiveis
GET {{base_url}}/providers/dffdae8f-fb53-4743-9152-e17367897ded/day-availability
Authorization: {{token}}

content
{
	"day": 11,
	"month": 12,
	"year": 2020
}
